import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '@components/Header'
import { ContainerWrap } from '@components/wrap/ContainerWrap'

const Home: NextPage = () => {
  return (
    <ContainerWrap>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* <EmotionStyleSample /> */}
      {/* <Navbar /> */}
      {/* <MainWrap>
        <Title />

        <Description />

        <CardList />
      </MainWrap> */}
      {/* <Footer /> */}
    </ContainerWrap>
  )
}

export default Home
