import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '@components/Header'
import { ContainerWrap } from '@components/wrap/ContainerWrap'
import { Repetition } from '@feature/repetition/components'

const Home: NextPage = () => {
  return (
    <ContainerWrap>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Repetition />

      {/* <EmotionStyleSample /> */}
      {/* <Navbar /> */}
      {/* <MainWrap>
        <Title />

        <Description />

        <CardList />
      </MainWrap> */}
      {/* <Footer /> */}
    </ContainerWrap>
  )
}

export default Home
