import type { NextPage } from 'next'
import Head from 'next/head'

import Title from '@components/Title'
import Description from '@components/Description'
import CardList from '@components/CardList'
import Footer from '@components/Footer'

import { ContainerWrap } from '@components/wrap/ContainerWrap'
import { MainWrap } from '@components/wrap/MainWrap'

const Home: NextPage = () => {
  return (
    <ContainerWrap>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainWrap>
        <Title />

        <Description />

        <CardList />
      </MainWrap>

      <Footer />
    </ContainerWrap>
  )
}

export default Home
